### ISSUE TITLE
Windows上小さなファイルのプレビューを見ようとするとバイナリだとおこられます

### ISSUE THREAD

**Issue by mirachan010** [yuki-yano/fern-preview.vim#13]
vim8.2.2927
Windows 21H1 OSビルド19043.985

最小構成
~/test/fern.vim
~/test/fern-preview.vim
にそれぞれをclone

vimrc
```
set encoding=utf-8
scriptencoding utf-8
set fileencoding=utf-8
set rtp+=~/test/fern.vim
set rtp+=~/test/fern-preview.vim

augroup VimrcFern
	autocmd!
	autocmd FileType fern nmap <silent> <buffer> p     <Plug>(fern-action-preview:auto:toggle)
augroup END
let mapleader = "\<Space>"
nnoremap <leader>f <cmd>Fern . -drawer -toggle<CR>
```

この状態でどのファイルをプレビューしようともBinary fileと言われてしまいプレビューを閲覧することができません
![image](https://user-images.githubusercontent.com/37107329/120505223-be32a900-c3ff-11eb-8b66-ec2a7cbebd7b.png)

**Comment by yuki-yano** [comment]
In the meantime, I removed the binary detection logic to deal with it.
I will consider the implementation again.
https://github.com/yuki-yano/fern-preview.vim/commit/6315af42391084188a4763f1c9e5523228e5d50e
